source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'statsample'
gem 'terminal-table'
gem 'multi_json'
gem 'trollop'
gem 'ohai', '~> 13.6'
gem 'memoizer'
gem 'byebug'
gem 'colorize'
gem 'rails'
gem 'get_process_mem'